import type { Roadmap } from "@/types";

/**
 * Static fallback roadmaps used when the backend has no data.
 * Each roadmap is hand-curated for a coherent learning path.
 */
export const STATIC_ROADMAPS: Record<string, Roadmap> = {
  /* ──────────────────  PYTHON  ────────────────── */
  python: {
    language: "python",
    title: "Python Mastery",
    description:
      "From first script to production-grade systems — types, OOP, async, data tooling, and deployment.",
    total_topics: 24,
    sections: [
      { id: "py-basics", title: "Fundamentals", icon: "🐍",
        description: "Syntax, types and control flow",
        topics: [
          { id: "py-syntax", title: "Syntax & Variables", description: "Indentation, naming, dynamic typing" },
          { id: "py-types", title: "Built-in Types", description: "int, float, str, list, dict, set, tuple" },
          { id: "py-control", title: "Control Flow", description: "if/elif/else, for, while, comprehensions" },
          { id: "py-funcs", title: "Functions", description: "Args, kwargs, *args, **kwargs, lambdas" },
        ],
      },
      { id: "py-oop", title: "Object-Oriented Python", icon: "🧱",
        description: "Classes, inheritance and design",
        topics: [
          { id: "py-classes", title: "Classes & Instances", description: "__init__, self, attributes, methods" },
          { id: "py-inherit", title: "Inheritance & MRO", description: "Single, multiple, super(), method resolution" },
          { id: "py-dunder", title: "Dunder Methods", description: "__str__, __repr__, __eq__, __hash__, operator overloading" },
          { id: "py-dataclasses", title: "Dataclasses & Pydantic", description: "Modern data containers and validation" },
        ],
      },
      { id: "py-stdlib", title: "Standard Library", icon: "📚",
        description: "Powerful built-in modules",
        topics: [
          { id: "py-collections", title: "collections & itertools", description: "Counter, defaultdict, deque, chain, groupby" },
          { id: "py-functools", title: "functools", description: "lru_cache, partial, reduce, wraps" },
          { id: "py-pathlib", title: "pathlib & os", description: "Modern file paths and OS interaction" },
          { id: "py-datetime", title: "datetime & zoneinfo", description: "Timezone-aware date/time handling" },
        ],
      },
      { id: "py-advanced", title: "Advanced Python", icon: "⚡",
        description: "Pro-level language features",
        topics: [
          { id: "py-generators", title: "Generators & Iterators", description: "yield, generator expressions, lazy evaluation" },
          { id: "py-decorators", title: "Decorators", description: "Function and class decorators with arguments" },
          { id: "py-context", title: "Context Managers", description: "with statement, contextlib, __enter__/__exit__" },
          { id: "py-async", title: "asyncio & async/await", description: "Coroutines, tasks, gather, event loop" },
        ],
      },
      { id: "py-data", title: "Data & Scientific Stack", icon: "📊",
        description: "NumPy, pandas, plotting",
        topics: [
          { id: "py-numpy", title: "NumPy", description: "ndarrays, broadcasting, vectorisation" },
          { id: "py-pandas", title: "pandas", description: "DataFrames, joins, groupby, time series" },
          { id: "py-plotting", title: "Matplotlib & Plotly", description: "Static and interactive visualisations" },
          { id: "py-jupyter", title: "Jupyter & notebooks", description: "Interactive analysis and reproducibility" },
        ],
      },
      { id: "py-prod", title: "Production Python", icon: "🚀",
        description: "Quality, performance, deployment",
        topics: [
          { id: "py-testing", title: "Testing with pytest", description: "Fixtures, parametrize, mocks, coverage" },
          { id: "py-typing", title: "Type Hints & mypy", description: "Static typing for safer code" },
          { id: "py-packaging", title: "Packaging & uv/poetry", description: "Virtual envs, dependencies, PyPI publishing" },
          { id: "py-perf", title: "Performance & Profiling", description: "cProfile, line_profiler, Cython, multiprocessing" },
        ],
      },
    ],
  },

  /* ──────────────────  JAVASCRIPT  ────────────────── */
  javascript: {
    language: "javascript",
    title: "Modern JavaScript",
    description:
      "ES2024+ language essentials, the browser DOM, asynchrony, and the modern tooling ecosystem.",
    total_topics: 24,
    sections: [
      { id: "js-core", title: "Language Core", icon: "⚡",
        description: "Modern syntax and semantics",
        topics: [
          { id: "js-vars", title: "let / const / scope", description: "Block scoping, hoisting, TDZ" },
          { id: "js-types", title: "Types & Coercion", description: "Primitives, objects, ==/===, typeof" },
          { id: "js-funcs", title: "Functions & Closures", description: "Arrow fns, this, closures, IIFE" },
          { id: "js-objects", title: "Objects & Destructuring", description: "Spread/rest, optional chaining, nullish coalescing" },
        ],
      },
      { id: "js-arrays", title: "Arrays & Iteration", icon: "🗂️",
        description: "Functional collection processing",
        topics: [
          { id: "js-array-methods", title: "Array Methods", description: "map, filter, reduce, find, some, every" },
          { id: "js-iter", title: "Iterators & Generators", description: "Symbol.iterator, function*, yield" },
          { id: "js-collections", title: "Map, Set, WeakMap", description: "When to choose which collection" },
        ],
      },
      { id: "js-async", title: "Asynchronous JS", icon: "⏳",
        description: "Promises and async patterns",
        topics: [
          { id: "js-event-loop", title: "Event Loop", description: "Stack, queues, microtasks, macrotasks" },
          { id: "js-promises", title: "Promises", description: ".then/.catch, Promise.all/race/allSettled" },
          { id: "js-async-await", title: "async / await", description: "Sequencing, parallelism, error handling" },
          { id: "js-fetch", title: "Fetch & Streams", description: "Modern HTTP, AbortController, ReadableStream" },
        ],
      },
      { id: "js-dom", title: "DOM & Browser APIs", icon: "🌐",
        description: "The web platform",
        topics: [
          { id: "js-dom-api", title: "DOM Manipulation", description: "querySelector, classList, dataset" },
          { id: "js-events", title: "Events & Delegation", description: "Bubbling, capturing, custom events" },
          { id: "js-storage", title: "Storage & Cookies", description: "localStorage, sessionStorage, IndexedDB" },
          { id: "js-workers", title: "Web Workers", description: "Background threads, message passing" },
        ],
      },
      { id: "js-oop", title: "OOP & Patterns", icon: "🧩",
        description: "Classes, prototypes, design patterns",
        topics: [
          { id: "js-prototypes", title: "Prototypes & Inheritance", description: "Prototype chain, Object.create" },
          { id: "js-classes", title: "Classes", description: "constructor, static, private fields, getters/setters" },
          { id: "js-modules", title: "ES Modules", description: "import/export, dynamic import, tree shaking" },
        ],
      },
      { id: "js-tooling", title: "Tooling & Quality", icon: "🛠️",
        description: "Build, test, ship",
        topics: [
          { id: "js-typescript", title: "TypeScript Essentials", description: "Types, interfaces, generics, narrowing" },
          { id: "js-bundlers", title: "Bundlers (Vite, esbuild)", description: "Modern build pipelines" },
          { id: "js-testing", title: "Testing (Vitest/Jest)", description: "Unit, integration, mocks, coverage" },
          { id: "js-lint", title: "ESLint & Prettier", description: "Code style, autofix, formatting" },
          { id: "js-frameworks", title: "Framework Landscape", description: "React, Vue, Svelte, Solid — when to choose what" },
          { id: "js-perf", title: "Performance", description: "Bundle size, lazy loading, Core Web Vitals" },
        ],
      },
    ],
  },

  /* ──────────────────  DSA  ────────────────── */
  dsa: {
    language: "dsa",
    title: "Data Structures & Algorithms",
    description:
      "Master DSA from fundamentals to advanced competitive programming — arrays, graphs, dynamic programming and beyond.",
    total_topics: 32,
    sections: [
      { id: "fundamentals", title: "Fundamentals", icon: "🔢",
        description: "Complexity analysis and mathematical foundations",
        topics: [
          { id: "big-o", title: "Big O Notation", description: "Time and space complexity analysis" },
          { id: "recursion", title: "Recursion & Backtracking", description: "Base cases, call stack, recursive thinking" },
          { id: "math-dsa", title: "Math for DSA", description: "Modular arithmetic, primes, GCD/LCM" },
        ],
      },
      { id: "arrays-strings", title: "Arrays & Strings", icon: "📊",
        description: "Core linear data structures and manipulation",
        topics: [
          { id: "array-ops", title: "Array Operations", description: "Two pointers, sliding window, prefix sums" },
          { id: "sorting", title: "Sorting Algorithms", description: "Bubble, Merge, Quick, Heap, Counting sort" },
          { id: "binary-search", title: "Binary Search", description: "Classic binary search and its variations" },
          { id: "string-algos", title: "String Algorithms", description: "Pattern matching, KMP, Rabin-Karp" },
        ],
      },
      { id: "linked-lists", title: "Linked Lists", icon: "🔗",
        description: "Dynamic linear data structures",
        topics: [
          { id: "singly-ll", title: "Singly Linked List", description: "Traversal, insertion, deletion, reversal" },
          { id: "doubly-ll", title: "Doubly Linked List", description: "Bidirectional traversal and operations" },
          { id: "ll-problems", title: "Classic LL Problems", description: "Cycle detection, merge, find middle" },
        ],
      },
      { id: "stacks-queues", title: "Stacks & Queues", icon: "📚",
        description: "LIFO / FIFO and priority-based structures",
        topics: [
          { id: "stack", title: "Stack", description: "Implementation, monotonic stack, next greater element" },
          { id: "queue", title: "Queue & Deque", description: "BFS, circular queue, sliding window maximum" },
          { id: "heap", title: "Priority Queue / Heap", description: "Min-heap, max-heap, K-th largest element" },
        ],
      },
      { id: "trees", title: "Trees", icon: "🌳",
        description: "Hierarchical data structures",
        topics: [
          { id: "binary-tree", title: "Binary Trees", description: "Traversals, height, diameter, LCA" },
          { id: "bst", title: "Binary Search Tree", description: "Insert, delete, search, validation" },
          { id: "balanced-trees", title: "Balanced Trees", description: "AVL, Red-Black tree concepts" },
          { id: "trie", title: "Trie", description: "Prefix trees for string/autocomplete problems" },
          { id: "segment-tree", title: "Segment Tree", description: "Range queries and point/range updates" },
        ],
      },
      { id: "graphs", title: "Graphs", icon: "🕸️",
        description: "Network traversal and shortest path algorithms",
        topics: [
          { id: "graph-repr", title: "Graph Representation", description: "Adjacency list, matrix, edge list" },
          { id: "bfs-dfs", title: "BFS & DFS", description: "Level-order, connected components, islands" },
          { id: "shortest-path", title: "Shortest Path", description: "Dijkstra, Bellman-Ford, Floyd-Warshall" },
          { id: "mst", title: "Minimum Spanning Tree", description: "Prim's and Kruskal's algorithms" },
          { id: "topological", title: "Topological Sort", description: "DAG ordering, course schedule, cycle detection" },
          { id: "union-find", title: "Union Find (DSU)", description: "Disjoint set union with path compression" },
        ],
      },
      { id: "dynamic-programming", title: "Dynamic Programming", icon: "⚡",
        description: "Optimization through memoization and tabulation",
        topics: [
          { id: "dp-basics", title: "DP Fundamentals", description: "Memoization vs tabulation, overlapping subproblems" },
          { id: "dp-1d", title: "1D DP", description: "Fibonacci, climbing stairs, house robber, coin change" },
          { id: "dp-2d", title: "2D DP", description: "Grid problems, unique paths, edit distance" },
          { id: "dp-knapsack", title: "Knapsack DP", description: "0/1, unbounded, partition equal subset" },
          { id: "dp-subsequence", title: "Subsequence DP", description: "LCS, LIS, palindromic subsequence" },
          { id: "dp-interval", title: "Interval DP", description: "Matrix chain multiplication, burst balloons" },
        ],
      },
      { id: "advanced", title: "Advanced Topics", icon: "🚀",
        description: "Competitive programming essentials",
        topics: [
          { id: "bit-manip", title: "Bit Manipulation", description: "Bitwise tricks, XOR problems, subset enumeration" },
          { id: "greedy", title: "Greedy Algorithms", description: "Activity selection, interval scheduling, jump game" },
          { id: "number-theory", title: "Number Theory", description: "Sieve of Eratosthenes, modular exponentiation" },
          { id: "divide-conquer", title: "Divide & Conquer", description: "Merge sort, quick select, closest pair" },
        ],
      },
    ],
  },

  /* ──────────────────  MACHINE LEARNING  ────────────────── */
  "machine-learning": {
    language: "machine-learning",
    title: "Machine Learning",
    description:
      "End-to-end ML — from the math underneath to model selection, evaluation and deployment.",
    total_topics: 24,
    sections: [
      { id: "ml-math", title: "Math Foundations", icon: "📐",
        description: "Linear algebra, calculus, probability, statistics",
        topics: [
          { id: "ml-linalg", title: "Linear Algebra", description: "Vectors, matrices, eigenvalues, SVD" },
          { id: "ml-calc", title: "Calculus & Gradients", description: "Derivatives, chain rule, gradient descent" },
          { id: "ml-prob", title: "Probability", description: "Distributions, Bayes' theorem, expectation" },
          { id: "ml-stats", title: "Statistics", description: "Hypothesis testing, p-values, confidence intervals" },
        ],
      },
      { id: "ml-data", title: "Data Preparation", icon: "🧹",
        description: "Get data ready for modelling",
        topics: [
          { id: "ml-eda", title: "Exploratory Data Analysis", description: "Distributions, correlations, outliers" },
          { id: "ml-cleaning", title: "Cleaning & Imputation", description: "Missing values, duplicates, type fixes" },
          { id: "ml-features", title: "Feature Engineering", description: "Encoding, scaling, polynomial features, binning" },
          { id: "ml-split", title: "Train / Val / Test Splits", description: "Random, stratified, time-series splits" },
        ],
      },
      { id: "ml-supervised", title: "Supervised Learning", icon: "🎯",
        description: "Regression and classification",
        topics: [
          { id: "ml-linear-reg", title: "Linear Regression", description: "OLS, regularisation (Ridge, Lasso)" },
          { id: "ml-logistic", title: "Logistic Regression", description: "Binary and multi-class classification" },
          { id: "ml-trees", title: "Decision Trees", description: "Splitting, gini/entropy, pruning" },
          { id: "ml-knn", title: "K-Nearest Neighbours", description: "Distance metrics, curse of dimensionality" },
          { id: "ml-svm", title: "Support Vector Machines", description: "Margins, kernels, soft margin" },
        ],
      },
      { id: "ml-ensemble", title: "Ensemble Methods", icon: "🧠",
        description: "Combine models for higher accuracy",
        topics: [
          { id: "ml-bagging", title: "Bagging & Random Forests", description: "Bootstrap, feature subsetting" },
          { id: "ml-boosting", title: "Boosting (XGBoost, LightGBM)", description: "Sequential weak learners" },
          { id: "ml-stacking", title: "Stacking & Blending", description: "Meta-learners over base models" },
        ],
      },
      { id: "ml-unsup", title: "Unsupervised Learning", icon: "🔍",
        description: "Patterns without labels",
        topics: [
          { id: "ml-kmeans", title: "K-Means & Hierarchical", description: "Clustering algorithms and choosing K" },
          { id: "ml-pca", title: "PCA & Dimensionality Reduction", description: "Principal components, t-SNE, UMAP" },
          { id: "ml-anomaly", title: "Anomaly Detection", description: "Isolation forests, one-class SVM" },
        ],
      },
      { id: "ml-eval", title: "Evaluation & Validation", icon: "📊",
        description: "Trustworthy model assessment",
        topics: [
          { id: "ml-metrics", title: "Metrics", description: "Accuracy, precision/recall, F1, ROC-AUC, MAE/MSE" },
          { id: "ml-cv", title: "Cross-Validation", description: "K-fold, stratified, leave-one-out" },
          { id: "ml-bias", title: "Bias / Variance Trade-off", description: "Underfitting vs overfitting, learning curves" },
          { id: "ml-tuning", title: "Hyperparameter Tuning", description: "Grid, random, Bayesian (Optuna)" },
        ],
      },
      { id: "ml-mlops", title: "MLOps & Deployment", icon: "🚢",
        description: "From notebook to production",
        topics: [
          { id: "ml-pipeline", title: "Pipelines & Reproducibility", description: "scikit-learn pipelines, MLflow" },
          { id: "ml-serve", title: "Model Serving", description: "REST APIs, batch vs online inference" },
        ],
      },
    ],
  },

  /* ──────────────────  DEEP LEARNING  ────────────────── */
  "deep-learning": {
    language: "deep-learning",
    title: "Deep Learning",
    description:
      "From perceptrons to modern transformers — neural networks, training, and the architectures powering today's AI.",
    total_topics: 22,
    sections: [
      { id: "dl-foundations", title: "Neural Network Foundations", icon: "🧠",
        description: "How neural nets actually work",
        topics: [
          { id: "dl-perceptron", title: "Perceptron & MLP", description: "Neurons, layers, activation functions" },
          { id: "dl-backprop", title: "Backpropagation", description: "Chain rule applied to networks" },
          { id: "dl-loss", title: "Loss Functions", description: "MSE, cross-entropy, custom losses" },
          { id: "dl-optimizers", title: "Optimizers", description: "SGD, Momentum, Adam, AdamW" },
        ],
      },
      { id: "dl-training", title: "Training Techniques", icon: "🏋️",
        description: "Make networks converge well",
        topics: [
          { id: "dl-init", title: "Initialisation", description: "Xavier, He, why it matters" },
          { id: "dl-batchnorm", title: "Normalisation", description: "Batch norm, layer norm, group norm" },
          { id: "dl-regularisation", title: "Regularisation", description: "Dropout, weight decay, label smoothing" },
          { id: "dl-lr", title: "Learning Rate Scheduling", description: "Warmup, cosine, one-cycle policy" },
        ],
      },
      { id: "dl-cnn", title: "Convolutional Networks", icon: "🖼️",
        description: "Vision architectures",
        topics: [
          { id: "dl-conv", title: "Convolutions & Pooling", description: "Kernels, stride, padding, receptive field" },
          { id: "dl-cnn-arch", title: "Classic CNNs", description: "LeNet, AlexNet, VGG, ResNet, EfficientNet" },
          { id: "dl-detection", title: "Object Detection", description: "YOLO, Faster R-CNN, anchor boxes" },
          { id: "dl-segmentation", title: "Segmentation", description: "U-Net, Mask R-CNN, semantic vs instance" },
        ],
      },
      { id: "dl-seq", title: "Sequence Models", icon: "🔁",
        description: "RNNs and beyond",
        topics: [
          { id: "dl-rnn", title: "RNNs & LSTMs", description: "Recurrence, vanishing gradients, gates" },
          { id: "dl-attention", title: "Attention Mechanisms", description: "Soft, hard, self-attention" },
        ],
      },
      { id: "dl-transformers", title: "Transformers", icon: "⚡",
        description: "The architecture behind modern AI",
        topics: [
          { id: "dl-trans-arch", title: "Transformer Architecture", description: "Encoder-decoder, multi-head attention" },
          { id: "dl-bert", title: "BERT & Encoder Models", description: "Masked LM, fine-tuning for NLP" },
          { id: "dl-gpt", title: "GPT & Decoder Models", description: "Causal LM, autoregressive generation" },
          { id: "dl-vit", title: "Vision Transformers (ViT)", description: "Patches, positional embeddings for images" },
        ],
      },
      { id: "dl-frameworks", title: "Frameworks & Tools", icon: "🛠️",
        description: "Ship deep learning at scale",
        topics: [
          { id: "dl-pytorch", title: "PyTorch", description: "Tensors, autograd, nn.Module, training loops" },
          { id: "dl-lightning", title: "PyTorch Lightning", description: "Removing training boilerplate" },
          { id: "dl-hf", title: "Hugging Face", description: "transformers, datasets, accelerate" },
          { id: "dl-deploy", title: "Deployment & Serving", description: "ONNX, TorchScript, Triton, distillation" },
        ],
      },
    ],
  },

  /* ──────────────────  GENERATIVE AI  ────────────────── */
  "generative-ai": {
    language: "generative-ai",
    title: "Generative AI",
    description:
      "Build with foundation models — prompting, RAG, fine-tuning, agents, and multimodal generation.",
    total_topics: 22,
    sections: [
      { id: "gen-foundations", title: "Foundation Models", icon: "🧬",
        description: "What modern LLMs are and how they work",
        topics: [
          { id: "gen-llm-intro", title: "LLM Fundamentals", description: "Tokenisation, context windows, sampling" },
          { id: "gen-models", title: "Model Landscape", description: "GPT-4, Claude, Llama, Mistral, Gemini" },
          { id: "gen-emergent", title: "Emergent Abilities", description: "Scaling laws, in-context learning" },
        ],
      },
      { id: "gen-prompting", title: "Prompt Engineering", icon: "✍️",
        description: "Get great outputs from LLMs",
        topics: [
          { id: "gen-prompt-basics", title: "Prompt Basics", description: "System, user, assistant roles" },
          { id: "gen-few-shot", title: "Few-Shot Learning", description: "In-context examples, format demonstrations" },
          { id: "gen-cot", title: "Chain-of-Thought", description: "Reasoning step by step, self-consistency" },
          { id: "gen-structured", title: "Structured Outputs", description: "JSON mode, function calling, tool use" },
        ],
      },
      { id: "gen-rag", title: "Retrieval-Augmented Generation", icon: "📚",
        description: "Ground LLMs in your data",
        topics: [
          { id: "gen-embeddings", title: "Embeddings", description: "Semantic vectors, similarity search" },
          { id: "gen-vectordb", title: "Vector Databases", description: "Pinecone, Weaviate, pgvector, Chroma" },
          { id: "gen-chunking", title: "Chunking & Indexing", description: "Document splitting strategies" },
          { id: "gen-rag-pipeline", title: "RAG Pipelines", description: "Retrieve → rerank → generate" },
          { id: "gen-rag-eval", title: "Evaluating RAG", description: "Faithfulness, relevance, RAGAs" },
        ],
      },
      { id: "gen-finetune", title: "Fine-Tuning & Adaptation", icon: "🎚️",
        description: "Customise models for your domain",
        topics: [
          { id: "gen-sft", title: "Supervised Fine-Tuning", description: "Instruction datasets, training loops" },
          { id: "gen-lora", title: "LoRA & QLoRA", description: "Parameter-efficient fine-tuning" },
          { id: "gen-rlhf", title: "RLHF & DPO", description: "Aligning models with human preferences" },
        ],
      },
      { id: "gen-multimodal", title: "Multimodal Generation", icon: "🎨",
        description: "Beyond text",
        topics: [
          { id: "gen-image", title: "Image Generation", description: "Diffusion models, Stable Diffusion, DALL-E" },
          { id: "gen-vision", title: "Vision-Language Models", description: "CLIP, GPT-4V, Claude vision" },
          { id: "gen-audio", title: "Audio & Speech", description: "Whisper, TTS, music generation" },
          { id: "gen-video", title: "Video Generation", description: "Sora, Runway, video diffusion" },
        ],
      },
      { id: "gen-tooling", title: "Tooling & Production", icon: "🚀",
        description: "Build and ship LLM apps",
        topics: [
          { id: "gen-langchain", title: "LangChain & LlamaIndex", description: "Orchestration frameworks" },
          { id: "gen-eval", title: "LLM Evaluation", description: "Benchmarks, LLM-as-judge, golden sets" },
          { id: "gen-safety", title: "Safety & Guardrails", description: "Prompt injection, content moderation, PII" },
        ],
      },
    ],
  },

  /* ──────────────────  AGENTIC AI  ────────────────── */
  "agentic-ai": {
    language: "agentic-ai",
    title: "Agentic AI",
    description:
      "Design autonomous AI agents — tool use, memory, planning, multi-agent systems, and production deployment.",
    total_topics: 20,
    sections: [
      { id: "agent-foundations", title: "Agent Foundations", icon: "🤖",
        description: "What an AI agent really is",
        topics: [
          { id: "agent-intro", title: "What is an Agent?", description: "Perception → reasoning → action loop" },
          { id: "agent-react", title: "ReAct Pattern", description: "Reasoning + acting in tandem" },
          { id: "agent-vs-pipeline", title: "Agent vs Pipeline", description: "When to use each, trade-offs" },
        ],
      },
      { id: "agent-tools", title: "Tool Use", icon: "🛠️",
        description: "Agents that act on the world",
        topics: [
          { id: "agent-fn-call", title: "Function Calling", description: "Schema-defined tools, JSON args" },
          { id: "agent-mcp", title: "MCP & Tool Protocols", description: "Model Context Protocol, OpenAPI tools" },
          { id: "agent-code-exec", title: "Code Execution", description: "Sandboxed Python, REPL agents" },
          { id: "agent-browser", title: "Browser & Computer Use", description: "Playwright agents, screen-grounded actions" },
        ],
      },
      { id: "agent-memory", title: "Memory Systems", icon: "🧠",
        description: "Give agents continuity",
        topics: [
          { id: "agent-short-mem", title: "Short-Term Memory", description: "Conversation buffers, summarisation" },
          { id: "agent-long-mem", title: "Long-Term Memory", description: "Vector stores, episodic memory" },
          { id: "agent-reflection", title: "Reflection & Self-Critique", description: "Improving via post-hoc reasoning" },
        ],
      },
      { id: "agent-planning", title: "Planning & Reasoning", icon: "🗺️",
        description: "Multi-step goal decomposition",
        topics: [
          { id: "agent-planner", title: "Plan-and-Execute", description: "Decompose goals into ordered steps" },
          { id: "agent-tot", title: "Tree of Thoughts", description: "Branching reasoning with backtracking" },
          { id: "agent-self-correct", title: "Self-Correction", description: "Verify, retry, repair on failure" },
        ],
      },
      { id: "agent-multi", title: "Multi-Agent Systems", icon: "👥",
        description: "Agents that collaborate",
        topics: [
          { id: "agent-roles", title: "Role-Based Agents", description: "Specialist agents (planner, coder, critic)" },
          { id: "agent-orchestration", title: "Orchestration Patterns", description: "Supervisor, swarm, graph topologies" },
          { id: "agent-comms", title: "Inter-Agent Communication", description: "Message passing, shared scratchpads" },
        ],
      },
      { id: "agent-prod", title: "Frameworks & Production", icon: "🚀",
        description: "Build, evaluate, deploy",
        topics: [
          { id: "agent-frameworks", title: "Frameworks", description: "LangGraph, CrewAI, AutoGen, Claude Agent SDK" },
          { id: "agent-eval", title: "Agent Evaluation", description: "Trajectory eval, success rate, cost" },
          { id: "agent-safety", title: "Safety & Guardrails", description: "Permission gates, sandboxing, audit logs" },
          { id: "agent-cost", title: "Cost & Latency", description: "Caching, parallelism, model routing" },
        ],
      },
    ],
  },

  /* ──────────────────  TYPESCRIPT  ────────────────── */
  typescript: {
    language: "typescript",
    title: "TypeScript",
    description: "From plain JS to bullet-proof type-safe applications — generics, narrowing, advanced types, and tooling.",
    total_topics: 18,
    sections: [
      { id: "ts-basics", title: "Foundations", icon: "🛡️", description: "Why types and how they work",
        topics: [
          { id: "ts-why", title: "Why TypeScript", description: "Static checking, refactoring safety, IDE wins" },
          { id: "ts-primitives", title: "Primitives & Annotations", description: "string, number, boolean, literal types" },
          { id: "ts-arrays", title: "Arrays & Tuples", description: "T[], readonly, fixed-shape tuples" },
        ],
      },
      { id: "ts-objects", title: "Objects & Functions", icon: "🧩", description: "Shape your data and APIs",
        topics: [
          { id: "ts-interfaces", title: "Interfaces & Type Aliases", description: "When to use which, extends vs &" },
          { id: "ts-funcs", title: "Function Types", description: "Overloads, optional, rest, void vs never" },
          { id: "ts-objects-types", title: "Object Types & Index Signatures", description: "Required, optional, mapped keys" },
        ],
      },
      { id: "ts-generics", title: "Generics", icon: "🔮", description: "Reusable, type-safe abstractions",
        topics: [
          { id: "ts-generic-funcs", title: "Generic Functions", description: "T extends, default type params" },
          { id: "ts-generic-types", title: "Generic Types & Classes", description: "Box<T>, key/value containers" },
          { id: "ts-constraints", title: "Constraints & Inference", description: "T extends X, conditional inference" },
        ],
      },
      { id: "ts-advanced", title: "Advanced Types", icon: "⚡", description: "The TypeScript power lifts",
        topics: [
          { id: "ts-narrowing", title: "Narrowing & Discriminated Unions", description: "typeof, in, never exhaustiveness" },
          { id: "ts-utility", title: "Utility Types", description: "Partial, Pick, Omit, Record, ReturnType" },
          { id: "ts-conditional", title: "Conditional & Mapped Types", description: "T extends U ? X : Y, [K in K]" },
          { id: "ts-template-literal", title: "Template Literal Types", description: "Type-safe string patterns" },
        ],
      },
      { id: "ts-tooling", title: "Project & Tooling", icon: "🛠️", description: "Use TS in real projects",
        topics: [
          { id: "ts-tsconfig", title: "tsconfig.json", description: "strict, paths, module, target" },
          { id: "ts-decls", title: "Declaration Files", description: ".d.ts, ambient modules, global types" },
          { id: "ts-react", title: "TS with React", description: "Component props, hooks, events" },
          { id: "ts-perf", title: "Compile Performance", description: "incremental, project references" },
          { id: "ts-zod", title: "Runtime Validation (Zod)", description: "Bridge runtime → static types" },
        ],
      },
    ],
  },

  /* ──────────────────  JAVA  ────────────────── */
  java: {
    language: "java",
    title: "Java",
    description: "Enterprise-grade Java — JVM, OOP, concurrency, collections, and Spring fundamentals.",
    total_topics: 20,
    sections: [
      { id: "java-basics", title: "Core Java", icon: "☕", description: "Syntax and JVM",
        topics: [
          { id: "java-syntax", title: "Syntax & Variables", description: "Primitives, autoboxing, control flow" },
          { id: "java-classes", title: "Classes & Objects", description: "Constructors, this, packages" },
          { id: "java-strings", title: "Strings & StringBuilder", description: "Immutability, intern pool" },
          { id: "java-arrays", title: "Arrays & Loops", description: "for-each, multi-dimensional arrays" },
        ],
      },
      { id: "java-oop", title: "OOP Deep Dive", icon: "🧱", description: "The four pillars in Java",
        topics: [
          { id: "java-inherit", title: "Inheritance & Polymorphism", description: "extends, super, method overriding" },
          { id: "java-interfaces", title: "Interfaces & Abstract Classes", description: "default methods, marker interfaces" },
          { id: "java-encaps", title: "Encapsulation & Access", description: "private, protected, package-private" },
          { id: "java-generics", title: "Generics", description: "<T>, bounded, wildcards, type erasure" },
        ],
      },
      { id: "java-collections", title: "Collections & Streams", icon: "📚", description: "Data structures + functional API",
        topics: [
          { id: "java-list-set", title: "List, Set, Map", description: "ArrayList, HashSet, HashMap internals" },
          { id: "java-streams", title: "Stream API", description: "map, filter, reduce, collectors" },
          { id: "java-optional", title: "Optional & Lambdas", description: "Functional interfaces, method refs" },
        ],
      },
      { id: "java-concurrency", title: "Concurrency", icon: "🧵", description: "Threads done right",
        topics: [
          { id: "java-threads", title: "Threads & Runnable", description: "Thread, ExecutorService" },
          { id: "java-sync", title: "synchronized & Locks", description: "Race conditions, ReentrantLock" },
          { id: "java-future", title: "Future & CompletableFuture", description: "Async composition" },
        ],
      },
      { id: "java-prod", title: "Production Java", icon: "🚀", description: "Build, test, ship",
        topics: [
          { id: "java-exceptions", title: "Exceptions", description: "checked vs unchecked, try-with-resources" },
          { id: "java-jdbc", title: "JDBC & Connection Pools", description: "PreparedStatement, HikariCP" },
          { id: "java-gradle", title: "Maven & Gradle", description: "Dependencies, plugins, lifecycle" },
          { id: "java-spring", title: "Spring Boot Basics", description: "@RestController, dependency injection" },
          { id: "java-junit", title: "JUnit & Mockito", description: "Unit tests, mocks, assertions" },
          { id: "java-jvm", title: "JVM & GC", description: "Heap, stack, garbage collectors" },
        ],
      },
    ],
  },

  /* ──────────────────  C++  ────────────────── */
  cpp: {
    language: "cpp",
    title: "C++",
    description: "Modern C++17/20 — pointers, RAII, the STL, templates, move semantics, and competitive programming.",
    total_topics: 20,
    sections: [
      { id: "cpp-basics", title: "Core Language", icon: "🔧", description: "Syntax and memory model",
        topics: [
          { id: "cpp-syntax", title: "Syntax & Types", description: "Primitive types, auto, constexpr" },
          { id: "cpp-control", title: "Control Flow", description: "if, switch, range-for, structured bindings" },
          { id: "cpp-funcs", title: "Functions & References", description: "Pass by value/reference/pointer, default args" },
          { id: "cpp-pointers", title: "Pointers & Memory", description: "*, &, new/delete, dangling pointers" },
        ],
      },
      { id: "cpp-oop", title: "Classes & RAII", icon: "🧱", description: "Object-oriented C++",
        topics: [
          { id: "cpp-classes", title: "Classes & Constructors", description: "Special members, rule of 3/5/0" },
          { id: "cpp-inherit", title: "Inheritance & Virtual Methods", description: "vtable, override, final" },
          { id: "cpp-raii", title: "RAII & Smart Pointers", description: "unique_ptr, shared_ptr, weak_ptr" },
          { id: "cpp-move", title: "Move Semantics", description: "rvalue refs, std::move, perfect forwarding" },
        ],
      },
      { id: "cpp-stl", title: "STL", icon: "📦", description: "The standard template library",
        topics: [
          { id: "cpp-containers", title: "Containers", description: "vector, map, set, deque, unordered_*" },
          { id: "cpp-algos", title: "Algorithms", description: "sort, find, accumulate, transform" },
          { id: "cpp-iterators", title: "Iterators", description: "Categories, adaptors, ranges" },
        ],
      },
      { id: "cpp-templates", title: "Templates", icon: "🔮", description: "Generic compile-time programming",
        topics: [
          { id: "cpp-fn-templates", title: "Function & Class Templates", description: "Type parameters, template args" },
          { id: "cpp-specialisation", title: "Specialisation & SFINAE", description: "Compile-time dispatch" },
          { id: "cpp-concepts", title: "Concepts (C++20)", description: "Cleaner constraints than SFINAE" },
        ],
      },
      { id: "cpp-modern", title: "Modern C++ & Perf", icon: "⚡", description: "C++17/20 features and speed",
        topics: [
          { id: "cpp-lambda", title: "Lambdas & std::function", description: "Captures, mutable, generic lambdas" },
          { id: "cpp-threads", title: "Threading & atomics", description: "std::thread, mutex, atomic" },
          { id: "cpp-cpp20", title: "C++20 Highlights", description: "Ranges, coroutines, modules" },
          { id: "cpp-build", title: "CMake & Build Systems", description: "Targets, dependencies, packaging" },
          { id: "cpp-cp", title: "Competitive Programming Tricks", description: "Fast I/O, bitset, common patterns" },
        ],
      },
    ],
  },

  /* ──────────────────  GO  ────────────────── */
  go: {
    language: "go",
    title: "Go (Golang)",
    description: "Concurrent, simple, fast. Goroutines, channels, interfaces, and production patterns.",
    total_topics: 18,
    sections: [
      { id: "go-basics", title: "Core Go", icon: "🐹", description: "Syntax and idioms",
        topics: [
          { id: "go-syntax", title: "Syntax & Types", description: "var, :=, basic types, type inference" },
          { id: "go-control", title: "Control Flow", description: "if, for, switch, defer" },
          { id: "go-funcs", title: "Functions & Multiple Returns", description: "Named returns, variadic, closures" },
          { id: "go-pointers", title: "Pointers", description: "& and *, no pointer arithmetic" },
        ],
      },
      { id: "go-data", title: "Data Structures", icon: "📦", description: "Built-ins and patterns",
        topics: [
          { id: "go-slices", title: "Slices & Arrays", description: "make, append, len, cap" },
          { id: "go-maps", title: "Maps", description: "Hash tables, zero values, deletion" },
          { id: "go-structs", title: "Structs & Methods", description: "Value vs pointer receivers" },
          { id: "go-interfaces", title: "Interfaces", description: "Implicit implementation, empty interface" },
        ],
      },
      { id: "go-concurrency", title: "Concurrency", icon: "🧵", description: "The killer feature",
        topics: [
          { id: "go-goroutines", title: "Goroutines", description: "go keyword, lightweight threads" },
          { id: "go-channels", title: "Channels", description: "Send/receive, buffered, directional" },
          { id: "go-select", title: "select & Timeouts", description: "Multiplex channels, time.After" },
          { id: "go-sync", title: "sync & Atomic", description: "Mutex, WaitGroup, sync.Once" },
        ],
      },
      { id: "go-prod", title: "Production Go", icon: "🚀", description: "Build real services",
        topics: [
          { id: "go-errors", title: "Error Handling", description: "errors.Is, errors.As, error wrapping" },
          { id: "go-modules", title: "Modules & Packages", description: "go.mod, semantic versioning" },
          { id: "go-testing", title: "Testing & Benchmarks", description: "testing.T, table-driven tests, *B" },
          { id: "go-net", title: "net/http & gRPC", description: "Building APIs, middleware patterns" },
          { id: "go-context", title: "Context", description: "Cancellation, deadlines, request-scoped values" },
          { id: "go-perf", title: "pprof & Performance", description: "Profiling, escape analysis" },
        ],
      },
    ],
  },

  /* ──────────────────  REACT  ────────────────── */
  react: {
    language: "react",
    title: "React",
    description: "Modern React with hooks, state management, performance, and the surrounding ecosystem.",
    total_topics: 20,
    sections: [
      { id: "react-basics", title: "Foundations", icon: "⚛️", description: "Components and JSX",
        topics: [
          { id: "react-jsx", title: "JSX & Components", description: "Function components, props, children" },
          { id: "react-state", title: "useState & Events", description: "Local state, event handlers, controlled inputs" },
          { id: "react-effects", title: "useEffect", description: "Side effects, deps array, cleanup" },
          { id: "react-lifting", title: "Lifting State Up", description: "Sharing state between siblings" },
        ],
      },
      { id: "react-hooks", title: "Hooks Deep Dive", icon: "🪝", description: "Beyond useState",
        topics: [
          { id: "react-context", title: "useContext", description: "Avoid prop drilling, theme/auth providers" },
          { id: "react-reducer", title: "useReducer", description: "Complex state with reducers" },
          { id: "react-ref", title: "useRef & useImperativeHandle", description: "DOM refs, mutable values" },
          { id: "react-memo", title: "useMemo & useCallback", description: "When (and when not) to memoise" },
          { id: "react-custom", title: "Custom Hooks", description: "Extract reusable stateful logic" },
        ],
      },
      { id: "react-data", title: "Data Fetching & State", icon: "📡", description: "Server state vs client state",
        topics: [
          { id: "react-fetch", title: "Fetching with useEffect", description: "Loading states, race conditions" },
          { id: "react-query", title: "TanStack Query", description: "Caching, refetching, optimistic updates" },
          { id: "react-zustand", title: "Zustand & Redux", description: "Global client state — when, why, how" },
        ],
      },
      { id: "react-perf", title: "Performance & Patterns", icon: "⚡", description: "Make React fast",
        topics: [
          { id: "react-render", title: "Rendering Behavior", description: "When does React re-render?" },
          { id: "react-suspense", title: "Suspense & Concurrent React", description: "Streaming, useTransition" },
          { id: "react-keys", title: "Keys & Reconciliation", description: "Why keys matter, common pitfalls" },
          { id: "react-codeg", title: "Code Splitting", description: "React.lazy, dynamic imports" },
        ],
      },
      { id: "react-eco", title: "Ecosystem", icon: "🌐", description: "Routing, forms, testing",
        topics: [
          { id: "react-router", title: "React Router / Next.js Routing", description: "Routes, layouts, navigation" },
          { id: "react-forms", title: "Forms & Validation", description: "react-hook-form, zod schemas" },
          { id: "react-test", title: "Testing (RTL + Vitest)", description: "Render, fire events, assertions" },
          { id: "react-ssr", title: "SSR / SSG / ISR", description: "Server components, hydration" },
        ],
      },
    ],
  },

  /* ──────────────────  NODE.JS  ────────────────── */
  nodejs: {
    language: "nodejs",
    title: "Node.js",
    description: "Server-side JavaScript — event loop, streams, building APIs with Express, and production deployment.",
    total_topics: 18,
    sections: [
      { id: "node-basics", title: "Runtime Foundations", icon: "🟢", description: "How Node actually works",
        topics: [
          { id: "node-event-loop", title: "Event Loop", description: "Phases, microtasks, libuv" },
          { id: "node-modules", title: "Modules (CJS & ESM)", description: "require vs import, package.json" },
          { id: "node-async", title: "Callbacks → Promises → async/await", description: "Async patterns evolution" },
          { id: "node-fs", title: "File System & Path", description: "fs/promises, path.join" },
        ],
      },
      { id: "node-streams", title: "Streams & Buffers", icon: "🌊", description: "Backpressure-aware I/O",
        topics: [
          { id: "node-streams-types", title: "Readable, Writable, Transform", description: "When to use which" },
          { id: "node-pipeline", title: "Pipelines & Backpressure", description: "stream.pipeline, error handling" },
          { id: "node-buffer", title: "Buffers & Encodings", description: "Binary data handling" },
        ],
      },
      { id: "node-http", title: "Building APIs", icon: "🛣️", description: "REST with Express / Fastify",
        topics: [
          { id: "node-express", title: "Express Fundamentals", description: "Routes, middleware, error handling" },
          { id: "node-rest", title: "REST API Patterns", description: "Versioning, status codes, idempotency" },
          { id: "node-validation", title: "Validation & Schemas", description: "zod, joi, class-validator" },
          { id: "node-auth", title: "Auth (JWT & sessions)", description: "Bcrypt, refresh tokens, RBAC" },
        ],
      },
      { id: "node-data", title: "Databases & Caching", icon: "🗄️", description: "Persist data, cache hot keys",
        topics: [
          { id: "node-orm", title: "Prisma & ORMs", description: "Schema-first, migrations, relations" },
          { id: "node-redis", title: "Redis Clients", description: "Caching, rate limiting, pubsub" },
          { id: "node-queue", title: "Job Queues (BullMQ)", description: "Background jobs, retries" },
        ],
      },
      { id: "node-prod", title: "Production", icon: "🚀", description: "Run Node reliably",
        topics: [
          { id: "node-cluster", title: "Cluster & PM2", description: "Multi-core, process managers" },
          { id: "node-perf", title: "Performance & Profiling", description: "clinic.js, flamegraphs" },
          { id: "node-test", title: "Testing (Vitest/Jest)", description: "Mocks, integration tests" },
          { id: "node-security", title: "Security Hardening", description: "Helmet, CORS, env handling" },
        ],
      },
    ],
  },

  /* ──────────────────  SYSTEM DESIGN  ────────────────── */
  "system-design": {
    language: "system-design",
    title: "System Design",
    description: "Design large-scale systems — load balancing, caching, sharding, queues, and end-to-end real-world architectures.",
    total_topics: 24,
    sections: [
      { id: "sd-fund", title: "Fundamentals", icon: "🏗️", description: "The vocabulary of scale",
        topics: [
          { id: "sd-scaling", title: "Vertical vs Horizontal Scaling", description: "Add CPU vs add machines" },
          { id: "sd-cap", title: "CAP Theorem & PACELC", description: "Consistency, availability, partition tolerance" },
          { id: "sd-latency", title: "Latency Numbers", description: "L1, RAM, SSD, network — orders of magnitude" },
          { id: "sd-availability", title: "SLA, SLO, SLI", description: "Five 9s, error budgets" },
        ],
      },
      { id: "sd-net", title: "Network & Communication", icon: "🌐", description: "How services talk",
        topics: [
          { id: "sd-lb", title: "Load Balancers", description: "L4 vs L7, round-robin, least-conn, sticky sessions" },
          { id: "sd-cdn", title: "CDN & Edge Caching", description: "PoPs, cache invalidation strategies" },
          { id: "sd-rest-grpc", title: "REST vs gRPC vs GraphQL", description: "When to choose what" },
          { id: "sd-websocket", title: "WebSockets & Long Polling", description: "Real-time push patterns" },
        ],
      },
      { id: "sd-db", title: "Databases at Scale", icon: "🗄️", description: "Storage strategies",
        topics: [
          { id: "sd-sql-nosql", title: "SQL vs NoSQL", description: "When to pick which" },
          { id: "sd-replication", title: "Replication", description: "Leader/follower, sync vs async" },
          { id: "sd-sharding", title: "Sharding Strategies", description: "Hash, range, geo-sharding" },
          { id: "sd-acid", title: "ACID & BASE", description: "Strong vs eventual consistency" },
          { id: "sd-indexes", title: "Indexes & Query Optimisation", description: "B-trees, hash, covering indexes" },
        ],
      },
      { id: "sd-cache", title: "Caching", icon: "⚡", description: "Read-fast layers",
        topics: [
          { id: "sd-cache-strategies", title: "Cache-aside, Write-through, Write-back", description: "Pattern trade-offs" },
          { id: "sd-eviction", title: "Eviction Policies", description: "LRU, LFU, TTL" },
          { id: "sd-cache-stampede", title: "Cache Stampede & Hot Keys", description: "Mitigations: locks, request coalescing" },
        ],
      },
      { id: "sd-async", title: "Async & Queues", icon: "📨", description: "Decouple producers from consumers",
        topics: [
          { id: "sd-mq", title: "Message Queues (Kafka/RabbitMQ)", description: "At-least-once, exactly-once, ordering" },
          { id: "sd-pubsub", title: "Pub/Sub", description: "Fan-out, topic partitioning" },
          { id: "sd-saga", title: "Sagas & Distributed Transactions", description: "Choreography vs orchestration" },
        ],
      },
      { id: "sd-real", title: "Real-World Designs", icon: "📐", description: "Classic interview problems",
        topics: [
          { id: "sd-url-shortener", title: "Design URL Shortener", description: "Hashing, base62, scale to 100M URLs" },
          { id: "sd-twitter", title: "Design Twitter Feed", description: "Fan-out on write vs read" },
          { id: "sd-chat", title: "Design WhatsApp", description: "WebSocket gateway, message ordering" },
          { id: "sd-uber", title: "Design Uber", description: "Geospatial, S2/H3, surge pricing" },
          { id: "sd-search", title: "Design Search Autocomplete", description: "Trie + ranking + caching" },
          { id: "sd-rate-limit", title: "Rate Limiting", description: "Token bucket, sliding window" },
        ],
      },
    ],
  },

  /* ──────────────────  SQL  ────────────────── */
  sql: {
    language: "sql",
    title: "SQL & Databases",
    description: "From SELECT to query plans — joins, indexes, transactions, window functions, and DBA-level optimisation.",
    total_topics: 18,
    sections: [
      { id: "sql-basics", title: "Fundamentals", icon: "🗄️", description: "Read and write data",
        topics: [
          { id: "sql-select", title: "SELECT, WHERE, ORDER BY", description: "Filter, project, sort" },
          { id: "sql-aggregate", title: "GROUP BY & Aggregates", description: "COUNT, SUM, AVG, HAVING" },
          { id: "sql-insert-update", title: "INSERT, UPDATE, DELETE", description: "Mutating data safely" },
        ],
      },
      { id: "sql-joins", title: "Joins & Sub-Queries", icon: "🔗", description: "Combine tables",
        topics: [
          { id: "sql-inner-outer", title: "INNER, LEFT, RIGHT, FULL", description: "When each is the right join" },
          { id: "sql-cross-self", title: "CROSS JOIN & Self-Join", description: "Pairings and hierarchies" },
          { id: "sql-subqueries", title: "Subqueries & CTEs", description: "Nested, correlated, WITH clause" },
        ],
      },
      { id: "sql-advanced", title: "Advanced SQL", icon: "🎯", description: "The interview-grade features",
        topics: [
          { id: "sql-windows", title: "Window Functions", description: "ROW_NUMBER, RANK, PARTITION BY" },
          { id: "sql-recursive", title: "Recursive CTEs", description: "Tree/graph traversal in pure SQL" },
          { id: "sql-pivot", title: "PIVOT & UNPIVOT", description: "Reshape rows ↔ columns" },
        ],
      },
      { id: "sql-modeling", title: "Schema Design", icon: "📐", description: "Build the right tables",
        topics: [
          { id: "sql-normal", title: "Normalisation (1NF–3NF)", description: "Avoid redundancy and anomalies" },
          { id: "sql-denorm", title: "Denormalisation Trade-offs", description: "Read perf vs write complexity" },
          { id: "sql-keys", title: "Primary, Foreign, Unique Keys", description: "Constraints that protect data" },
          { id: "sql-types", title: "Types & Storage", description: "VARCHAR vs TEXT, JSON, UUID" },
        ],
      },
      { id: "sql-perf", title: "Performance", icon: "⚡", description: "Make slow queries fast",
        topics: [
          { id: "sql-indexes", title: "Indexes Deep Dive", description: "B-tree, hash, partial, composite" },
          { id: "sql-explain", title: "EXPLAIN & Query Plans", description: "Read plans, fix N+1" },
          { id: "sql-tx", title: "Transactions & Isolation", description: "Read committed, repeatable read, serialisable" },
          { id: "sql-deadlock", title: "Locks & Deadlocks", description: "Detection, prevention" },
          { id: "sql-replication", title: "Replication & Failover", description: "Primary/replica, lag monitoring" },
        ],
      },
    ],
  },

  /* ──────────────────  DOCKER  ────────────────── */
  docker: {
    language: "docker",
    title: "Docker & Containers",
    description: "Containerise anything — images, layers, networks, volumes, multi-stage builds, and Docker Compose.",
    total_topics: 16,
    sections: [
      { id: "dk-basics", title: "Container Fundamentals", icon: "🐳", description: "Why containers exist",
        topics: [
          { id: "dk-vm-vs-container", title: "VMs vs Containers", description: "Kernel sharing, isolation models" },
          { id: "dk-namespaces", title: "Namespaces & Cgroups", description: "How Linux makes isolation cheap" },
          { id: "dk-images-vs-containers", title: "Images vs Containers", description: "Read-only template vs running instance" },
        ],
      },
      { id: "dk-images", title: "Images & Dockerfile", icon: "📦", description: "Build reproducible images",
        topics: [
          { id: "dk-dockerfile", title: "Writing a Dockerfile", description: "FROM, RUN, COPY, CMD, ENTRYPOINT" },
          { id: "dk-layers", title: "Layer Caching", description: "Order matters, .dockerignore" },
          { id: "dk-multistage", title: "Multi-Stage Builds", description: "Tiny final images" },
          { id: "dk-distroless", title: "Distroless & Alpine", description: "Minimal base images, security trade-offs" },
        ],
      },
      { id: "dk-runtime", title: "Running Containers", icon: "▶️", description: "Day-to-day commands",
        topics: [
          { id: "dk-run", title: "docker run essentials", description: "-d, -p, -v, -e, --name" },
          { id: "dk-volumes", title: "Volumes & Bind Mounts", description: "Persisting data correctly" },
          { id: "dk-network", title: "Networks", description: "bridge, host, custom networks, DNS" },
          { id: "dk-logs-exec", title: "logs, exec, ps", description: "Inspecting running containers" },
        ],
      },
      { id: "dk-compose", title: "Compose & Orchestration", icon: "🎼", description: "Multi-container stacks",
        topics: [
          { id: "dk-compose-yml", title: "docker-compose.yml", description: "Services, depends_on, env files" },
          { id: "dk-compose-dev", title: "Compose for Development", description: "Hot reload, override files" },
          { id: "dk-compose-prod", title: "Compose vs Kubernetes", description: "When to graduate" },
        ],
      },
      { id: "dk-prod", title: "Production Patterns", icon: "🚀", description: "Ship containers safely",
        topics: [
          { id: "dk-registry", title: "Registries & Tagging", description: "Docker Hub, GHCR, semantic tags" },
          { id: "dk-security", title: "Image Security Scanning", description: "Trivy, snyk, supply-chain" },
        ],
      },
    ],
  },

  /* ──────────────────  GIT  ────────────────── */
  git: {
    language: "git",
    title: "Git & GitHub",
    description: "Version control mastery — branching, rebasing, merging, recovery, and GitHub workflows.",
    total_topics: 16,
    sections: [
      { id: "git-basics", title: "Core Workflow", icon: "🌿", description: "Day-to-day commands",
        topics: [
          { id: "git-init", title: "init, status, add, commit", description: "Your first repo" },
          { id: "git-config", title: "Config & .gitignore", description: "User, ignore patterns" },
          { id: "git-log", title: "log & diff", description: "See history and changes" },
          { id: "git-undo", title: "Undoing Changes", description: "checkout, restore, reset (safe vs hard)" },
        ],
      },
      { id: "git-branches", title: "Branching", icon: "🌳", description: "Parallel work without conflicts",
        topics: [
          { id: "git-branch", title: "branch, switch, merge", description: "Branch creation and merging" },
          { id: "git-merge-strategies", title: "Merge Strategies", description: "Fast-forward, no-ff, octopus" },
          { id: "git-conflicts", title: "Resolving Merge Conflicts", description: "Read markers, choose changes" },
        ],
      },
      { id: "git-rebase", title: "Rebase & Cherry-Pick", icon: "✨", description: "Clean linear history",
        topics: [
          { id: "git-rebase-basics", title: "Rebase Fundamentals", description: "When to rebase vs merge" },
          { id: "git-interactive", title: "Interactive Rebase", description: "squash, edit, reorder commits" },
          { id: "git-cherry-pick", title: "Cherry-Pick", description: "Move single commits across branches" },
        ],
      },
      { id: "git-remote", title: "Remotes & Collaboration", icon: "🌐", description: "Work with others",
        topics: [
          { id: "git-remote-basics", title: "Remote, Push, Pull, Fetch", description: "Sync with origin" },
          { id: "git-pr", title: "Pull Requests", description: "Code review workflow on GitHub" },
          { id: "git-flows", title: "Git Flow vs Trunk-Based", description: "Branching strategies" },
        ],
      },
      { id: "git-recovery", title: "Recovery & Tools", icon: "🛟", description: "Get out of bad states",
        topics: [
          { id: "git-reflog", title: "Reflog & Recovery", description: "Find lost commits" },
          { id: "git-stash", title: "Stash & WIP", description: "Save work without committing" },
          { id: "git-bisect", title: "Bisect", description: "Binary-search a bug across commits" },
        ],
      },
    ],
  },

  
};
